name: "Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}

          touch testfile-${VERSION}

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            testfile-${VERSION}
