name: "Prerelease"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  contents: write

jobs:
  publish-prerelease:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Package
        id: package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}

          touch testfile-${VERSION}

          echo "::set-output name=version::${VERSION}"
      - name: Create prerelease
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            testfile-${{ steps.package.outputs.version }}
